package io.holixon.avro.adapter.common.converter

import io.holixon.avro.adapter.api.AvroSingleObjectEncoded
import io.holixon.avro.adapter.api.SchemaResolver
import io.holixon.avro.adapter.api.converter.SpecificRecordToSingleObjectConverter
import io.holixon.avro.adapter.api.ext.ByteArrayExt.toHexString
import io.holixon.avro.adapter.common.AvroAdapterDefault
import io.holixon.avro.adapter.common.AvroAdapterDefault.DecoderSpecificRecordClassResolver
import io.holixon.avro.adapter.common.AvroAdapterDefault.fromByteArray
import io.holixon.avro.adapter.common.AvroAdapterDefault.readPayloadAndSchemaId
import io.holixon.avro.adapter.common.AvroAdapterDefault.toByteArray
import org.apache.avro.specific.SpecificRecordBase
import org.apache.avro.util.ClassUtils

/**
 * Converts any instance derived from [SpecificRecordBase] (generated from avsc) to a [ByteArray] that follows the format specified
 * in the [avro specs](https://avro.apache.org/docs/current/spec.html#single_object_encoding).
 */
class DefaultSpecificRecordToSingleObjectConverter @JvmOverloads constructor(
  private val schemaResolver: SchemaResolver,
  private val decoderSpecificRecordClassResolver: DecoderSpecificRecordClassResolver = AvroAdapterDefault.reflectionBasedDecoderSpecificRecordClassResolver
) : SpecificRecordToSingleObjectConverter {

  override fun <T : SpecificRecordBase> encode(data: T): AvroSingleObjectEncoded = data.toByteArray()


  override fun <T : SpecificRecordBase> decode(bytes: AvroSingleObjectEncoded): T {

    // get the reader schema id from the single object encoded bytes
    val schemaId = bytes.readPayloadAndSchemaId().schemaId
    // load writer schema info from schema resolver
    val writerSchemaWithId = schemaResolver.apply(schemaId).orElseThrow { IllegalArgumentException("Can not resolve writer schema for id=$schemaId.") }
    // we have to assume that the namespace and name of the message payload did not change, so we try to load the class based on the schema info
    // of the writer schema. This might lead to another (earlier or later) revision, but the canonical name should not have changed.
    val targetClass: Class<SpecificRecordBase> =  decoderSpecificRecordClassResolver.apply(writerSchemaWithId)
    // then we use reflection to call the decoder function generated by avro and return the result
    @Suppress("UNCHECKED_CAST")
    return targetClass.fromByteArray(bytes) as T
  }
}

